# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker compose reference guide at
# https://docs.docker.com/compose/compose-file/

version: "3.7"

services:
  # NextJS App
  # app-next:
  #   build:
  #     context: .
  #   container_name: app-next
  #   environment:
  #     NODE_ENV: production
  #     MYSQL_HOST: ${MYSQL_HOST}
  #     MYSQL_DATABASE: ${MYSQL_DATABASE}
  #     MYSQL_USER: ${MYSQL_USER}
  #     MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  #     MQTT_HOST: ${MQTT_HOST}
  #     MQTT_WS_PORT: ${MQTT_PORT}
  #     MQTT_USER: ${MQTT_USER}
  #     MQTT_PASSWORD: ${MQTT_PASSWORD}
  #   ports:
  #     - ${APP_PORT}:3000

  # MySQL 8 Server
  app-db:
    image: mysql:8.0
    container_name: ${MYSQL_HOST}
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=caching_sha2_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"

  # Adminer MySQL Admin Tool
  # app-adminer:
  #   image: adminer
  #   container_name: app-adminer
  #   restart: always
  #   ports:
  #     - ${ADMINER_PORT}:8080

  # mqtt5 eclipse-mosquitto
  # mqtt5:
  #   image: eclipse-mosquitto
  #   container_name: ${MQTT_HOST}
  #   ports:
  #     - "${MQTT_PORT}:1883" #default mqtt port
  #     - "${MQTT_WS_PORT}:9001" #default mqtt port for websockets
  #   volumes:
  #     - mqtt-config:/mosquitto/config:rw
  #     - mqtt-data:/mosquitto/data:rw
  #     - mqtt-log:/mosquitto/log:rw

# volumes for mapping data,config and log
volumes:
  mqtt-config:
  mqtt-data:
  mqtt-log:
  mysql-data:

networks:
  default:
    name: app-network
